ignore:
  - "**/com/trendyol/stove/functional"
  - "**/com/trendyol/stove/testing/e2e/system/abstractions"
  - "**/com/trendyol/stove/testing/e2e/system/annotations"
  - "**/com/trendyol/stove/testing/e2e/serialization"
  - "**/com/trendyol/stove/testing/e2e/standalone"
  - "**/stove/spring/example"
  - "**/stove/ktor/example"
