site_name: "Stove"
repo_url: https://github.com/trendyol/stove4k
edit_uri: https://github.com/trendyol/stove4k/edit/main/docs
extra_css:
  - css/custom.css
plugins:
  - search
  - awesome-pages:
     collapse_single_pages: true
theme:
  name: material
  logo: assets/logo.png
  features:
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  homepage: "/"
