name: Build
on:
  push:
    branches: [ main ]
    paths:
      - ${{ env.PATH_EXAMPLES }}
      - ${{ env.PATH_LIB }}
      - ${{ env.PATH_STARTERS }}
      - ${{ env.PATH_GRADLE }}
      - ${{ env.PATH_GRADLE_KTS }}
      - ${{ env.PATH_SETTINGS_KTS }}
      - ${{ env.PATH_BUILD_SRC }}
  pull_request:
    branches: [ main ]
    paths:
      - ${{ env.PATH_EXAMPLES }}
      - ${{ env.PATH_LIB }}
      - ${{ env.PATH_STARTERS }}
      - ${{ env.PATH_GRADLE }}
      - ${{ env.PATH_GRADLE_KTS }}
      - ${{ env.PATH_SETTINGS_KTS }}
      - ${{ env.PATH_BUILD_SRC }}

env:
  PATH_EXAMPLES: 'examples/**'
  PATH_LIB: 'lib/**'
  PATH_STARTERS: 'starters/**'
  PATH_GRADLE: 'gradle/**'
  PATH_GRADLE_KTS: 'build.gradle.kts'
  PATH_SETTINGS_KTS: 'settings.gradle.kts'
  PATH_BUILD_SRC: 'buildSrc/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Gradle Build and Test
        uses: gradle/gradle-build-action@v3.3.2
        with:
          arguments: --build-cache build test koverXmlReport testAggregateXmlReports

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
