name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: 'temurin'

      - name: Check out Git repository
        uses: actions/checkout@v3
    
      - name: Gradle Build and Test
        run: |
           ./gradlew build test codeCoverageReport testAggregateReports
#       - name: Upload coverage to Codecov
#         uses: codecov/codecov-action@v3
#         with:
#           files: ./build/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
#           flags: unittests
#           name: codecov-umbrella
#           fail_ci_if_error: true
#           verbose: true
#           java-version: 11
